name: masrof
description: "masrof"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  # router manger
  go_router: ^14.3.0
  # responsive 
  flutter_screenutil: ^5.9.3
  # Svg 
  flutter_svg: ^2.0.10+1
  build_runner: ^2.4.13
  flutter_gen: ^5.8.0
  # state managment
  provider: ^6.1.2


  cupertino_icons: ^1.0.8

dev_dependencies:

  flutter_gen_runner:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/fonts/Agbalumo-Regular.ttf
    - assets/fonts/NotoSans-Regular.ttf

  fonts:
   - family: Agbalumo
     fonts:
       - asset: assets/fonts/Agbalumo-Regular.ttf
   - family: NotoSans
     fonts:
       - asset: assets/fonts/NotoSans-Regular.ttf


