name: masrof
description: "masrof"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # Router manager
  go_router: ^14.3.0
  # Responsive
  flutter_screenutil: ^5.9.3
  # SVG
  flutter_svg: ^2.0.17
  # State management
  provider: ^6.1.2
  syncfusion_flutter_charts: ^28.1.33
  state_extended: ^5.5.0
  data_table_2: ^2.5.15
  # Serializing models
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  copy_with_extension: ^5.0.4
  copy_with_extension_gen: ^5.0.4
  collection:
  intl:
  sqflite:
  sqflite_common_ffi: ^2.3.4+3
  path_provider: ^2.1.5
  shared_preferences: ^2.3.3
  get_it: ^8.0.2
  path: ^1.9.0
  dartz: ^0.10.1
  pdf: ^3.11.1
  open_file: ^3.5.10
  url_launcher: ^6.3.1
  syncfusion_flutter_pdfviewer: ^28.1.35
  cupertino_icons: ^1.0.8
  mason: ^0.1.1
#  Fire Base Tools
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2  
  google_sign_in: ^6.2.1
  google_sign_in_web: ^0.12.4+1
  platform_detector: ^0.2.0
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  assets:
    - i18n/
    - assets/images/
    - assets/fonts/
    - assets/fonts/Agbalumo-Regular.ttf
    - assets/fonts/NotoSans-Regular.ttf
    - assets/fonts/NotoKufiArabic-VariableFont_wght.ttf

  fonts:
    - family: Agbalumo
      fonts:
        - asset: assets/fonts/Agbalumo-Regular.ttf

    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf

    - family: NotoKufiArabic
      fonts:
        - asset: assets/fonts/NotoKufiArabic-VariableFont_wght.ttf
# for generating assets
flutter_assets:
  assets_path: assets/
  output_path: lib/utilites/constants/
  filename: assets.dart
  field_prefix: 
  ignore_comments: true
