name: masrof
description: "masrof"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # router manger
  go_router: ^14.3.0
  # responsive 
  flutter_screenutil: ^5.9.3
  # Svg 
  flutter_svg: ^2.0.10+1
  build_runner: ^2.4.13
  # state managment
  provider: ^6.1.2
  syncfusion_flutter_charts: ^27.1.53
  state_extended: ^5.5.0
  data_table_2: ^2.5.15
  # serializing models 
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  copy_with_extension: ^5.0.4
  copy_with_extension_gen: ^5.0.4
  collection:
  intl:
  sqflite:
  sqflite_common_ffi: ^2.3.4+3
  path_provider: ^2.1.5
  shared_preferences: ^2.3.3
  get_it: ^8.0.2
  path: ^1.9.0
  dartz: ^0.10.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_gen_runner:

  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
  - i18n/
  - assets/images/
  - assets/fonts/
  - assets/fonts/Agbalumo-Regular.ttf
  - assets/fonts/NotoSans-Regular.ttf
  - assets/fonts/NotoKufiArabic-VariableFont_wght.ttf

  fonts:
  - family: Agbalumo
    fonts:
    - asset: assets/fonts/Agbalumo-Regular.ttf

  - family: NotoSans
    fonts:
    - asset: assets/fonts/NotoSans-Regular.ttf

  - family: NotoKufiArabic
    fonts:
    - asset: assets/fonts/NotoKufiArabic-VariableFont_wght.ttf
