// ignore_for_file: public_member_api_docs,constant_identifier_names,type=lint,unused_element,unused_field
import 'package:flutter/foundation.dart';

//
// GENERATED CODE - DO NOT MODIFY BY HAND
// **************************************************************************
// Generated by flutter-assets-generator extension for VS Code
// @mrasityilmaz
// **************************************************************************

@immutable
final class Assets {
  Assets._();
  static final _Fonts fonts = _Fonts._();
  static final _Images images = _Images._();


}

@immutable
final class _Fonts {
  _Fonts._();

  final String agbalumo_regular_ttf = 'assets/fonts/Agbalumo-Regular.ttf';
  final String notokufiarabic_variablefont_wght_ttf = 'assets/fonts/NotoKufiArabic-VariableFont_wght.ttf';
  final String notosans_regular_ttf = 'assets/fonts/NotoSans-Regular.ttf';

}

@immutable
final class _Images {
  _Images._();

  final String app_logo_svg = 'assets/images/app_logo.svg';
  final String app_logo2_svg = 'assets/images/app_logo2.svg';
  final String home_svg = 'assets/images/home.svg';
  final String masruf_svg = 'assets/images/masruf.svg';
  final String menu_svg = 'assets/images/menu.svg';
  final String messages_svg = 'assets/images/messages.svg';
  final String profile_svg = 'assets/images/profile.svg';
  final String restore_svg = 'assets/images/restore.svg';
  final String save_svg = 'assets/images/save.svg';

}

